In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
import statsmodels.api as sm
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('Bank_data.csv')
df

     Unnamed: 0  interest_rate  credit  march  may  previous  duration    y
0             0          1.334     0.0    1.0  0.0       0.0     117.0   no
1             1          0.767     0.0    0.0  2.0       1.0     274.0  yes
2             2          4.858     0.0    1.0  0.0       0.0     167.0   no
3             3          4.120     0.0    0.0  0.0       0.0     686.0  yes
4             4          4.856     0.0    1.0  0.0       0.0     157.0   no
..          ...            ...     ...    ...  ...       ...       ...  ...
513         513          1.334     0.0    1.0  0.0       0.0     204.0   no
514         514          0.861     0.0    0.0  2.0       1.0     806.0  yes
515         515          0.879     0.0    0.0  0.0       0.0     290.0   no
516         516          0.877     0.0    0.0  5.0       1.0     473.0  yes
517         517          4.965     0.0    0.0  0.0       0.0     142.0   no

[518 rows x 8 columns]

In [5]:
df.drop(df.columns[df.columns.str.contains('Unnamed: 0', case = False)], axis = 1, inplace = True)

In [6]:
df

     interest_rate  credit  march  may  previous  duration    y
0            1.334     0.0    1.0  0.0       0.0     117.0   no
1            0.767     0.0    0.0  2.0       1.0     274.0  yes
2            4.858     0.0    1.0  0.0       0.0     167.0   no
3            4.120     0.0    0.0  0.0       0.0     686.0  yes
4            4.856     0.0    1.0  0.0       0.0     157.0   no
..             ...     ...    ...  ...       ...       ...  ...
513          1.334     0.0    1.0  0.0       0.0     204.0   no
514          0.861     0.0    0.0  2.0       1.0     806.0  yes
515          0.879     0.0    0.0  0.0       0.0     290.0   no
516          0.877     0.0    0.0  5.0       1.0     473.0  yes
517          4.965     0.0    0.0  0.0       0.0     142.0   no

[518 rows x 7 columns]

In [8]:
df.isnull().sum()

interest_rate    0
credit           0
march            0
may              0
previous         0
duration         0
y                0
dtype: int64

In [9]:
df['y'] = df['y'].map({'yes' : 1, 'no' : 0})
df

     interest_rate  credit  march  may  previous  duration  y
0            1.334     0.0    1.0  0.0       0.0     117.0  0
1            0.767     0.0    0.0  2.0       1.0     274.0  1
2            4.858     0.0    1.0  0.0       0.0     167.0  0
3            4.120     0.0    0.0  0.0       0.0     686.0  1
4            4.856     0.0    1.0  0.0       0.0     157.0  0
..             ...     ...    ...  ...       ...       ... ..
513          1.334     0.0    1.0  0.0       0.0     204.0  0
514          0.861     0.0    0.0  2.0       1.0     806.0  1
515          0.879     0.0    0.0  0.0       0.0     290.0  0
516          0.877     0.0    0.0  5.0       1.0     473.0  1
517          4.965     0.0    0.0  0.0       0.0     142.0  0

[518 rows x 7 columns]

In [10]:
X = df[['interest_rate', 'credit', 'march', 'may', 'previous', 'duration']]
y = df['y']

In [13]:
x0 = sm.add_constant(X)
reg_result = sm.Logit(y, X).fit()
reg_result.summary()

Optimization terminated successfully.
         Current function value: 0.336102
         Iterations 7

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  518
Model:                          Logit   Df Residuals:                      512
Method:                           MLE   Df Model:                            5
Date:                Tue, 12 Aug 2025   Pseudo R-squ.:                  0.5151
Time:                        16:17:27   Log-Likelihood:                -174.10
converged:                       True   LL-Null:                       -359.05
Covariance Type:            nonrobust   LLR p-value:                 9.078e-78
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
interest_rate    -0.7998      0.079    -10.180      0.000      -0.954      -0.646
credit            2.3241      1.072      2.169      0.030       0.224       4.424
march            -1.8497      0.316     -5.858      0.000      -2.469      -1.231
may               0.1579      0.210      0.752      0.452      -0.254       0.570
previous          1.2663      0.585      2.164      0.030       0.119       2.413
duration          0.0069      0.001     10.218      0.000       0.006       0.008
=================================================================================
"""

In [15]:
df_cleaned = df.drop(columns = ['may'])

In [17]:
X = df[['interest_rate', 'credit', 'march', 'previous', 'duration']]
y = df['y']

In [18]:
x0 = sm.add_constant(X)
reg_result = sm.Logit(y, X).fit()
reg_result.summary()

Optimization terminated successfully.
         Current function value: 0.336668
         Iterations 7

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  518
Model:                          Logit   Df Residuals:                      513
Method:                           MLE   Df Model:                            4
Date:                Tue, 12 Aug 2025   Pseudo R-squ.:                  0.5143
Time:                        16:24:23   Log-Likelihood:                -174.39
converged:                       True   LL-Null:                       -359.05
Covariance Type:            nonrobust   LLR p-value:                 1.185e-78
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
interest_rate    -0.8030      0.079    -10.201      0.000      -0.957      -0.649
credit            2.3459      1.071      2.190      0.029       0.246       4.445
march            -1.8387      0.315     -5.831      0.000      -2.457      -1.221
previous          1.5262      0.478      3.190      0.001       0.588       2.464
duration          0.0069      0.001     10.365      0.000       0.006       0.008
=================================================================================
"""

In [21]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif_data = pd.DataFrame()
vif_data["Feature"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i)
                   for i in range(X.shape[1])]

print(vif_data)

         Feature       VIF
0  interest_rate  1.695045
1         credit  1.041843
2          march  1.255612
3       previous  1.104914
4       duration  1.775069

In [22]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
result = LogisticRegression()

In [23]:
result.fit(X, y)

LogisticRegression()

In [24]:
y_pred = result.predict(x_test)

In [25]:
y_pred

array([1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0], dtype=int64)

In [26]:
from sklearn.metrics import confusion_matrix, classification_report
print("Classification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.88      0.87        59
           1       0.84      0.82      0.83        45

    accuracy                           0.86       104
   macro avg       0.85      0.85      0.85       104
weighted avg       0.86      0.86      0.86       104


Confusion Matrix:
 [[52  7]
 [ 8 37]]